# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vmarc\PycharmProjects\Prog2beadando\MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.NgBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NgBtn.setGeometry(QtCore.QRect(10, 20, 151, 51))
        self.NgBtn.setObjectName("NgBtn")
        self.ImgBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ImgBtn.setGeometry(QtCore.QRect(10, 90, 151, 51))
        self.ImgBtn.setObjectName("ImgBtn")
        self.DiffBox = QtWidgets.QComboBox(self.centralwidget)
        self.DiffBox.setGeometry(QtCore.QRect(10, 220, 151, 31))
        self.DiffBox.setObjectName("DiffBox")
        self.imgPathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.imgPathLineEdit.setGeometry(QtCore.QRect(10, 170, 271, 21))
        self.imgPathLineEdit.setObjectName("imgPathLineEdit")
        self.imgView = QtWidgets.QGraphicsView(self.centralwidget)
        self.imgView.setGeometry(QtCore.QRect(310, 10, 471, 551))
        self.imgView.setObjectName("imgView")
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "MainWindow"))
        self.NgBtn.setText(_translate("MainMenu", "Start Game"))
        self.ImgBtn.setText(_translate("MainMenu", "Load Image"))
        self.DiffBox.setPlaceholderText(_translate("MainMenu", "Select Difficulty"))
